### ISSUE TITLE
void fiend not gaining corruption on kill

### ISSUE THREAD

**Issue by aka-Syntax** [Moffein/RiskyMod#61]
checked config and gain corruption on kill was set to true
tried several runs and he kept not gaining corruption on kill

profile code: 0191f451-4423-27b8-14bc-de67b0a8848a

**Comment by Moffein** [comment]
Thanks for reporting this, the issue has been fixed.

**Comment by aka-Syntax** [comment]
just downloaded the 2.0.7 version and tried it again, he's still not gaining corruption on kill unfortunately :(
only other thing i downloaded alongside the update is cursecatcher 0.3.2 but i dont think that should break anything
did a couple runs for testing, he still gains corruption from taking damage and doesn't gain any from external healing (monster tooth) so it's only the on-kill corruption that isn't working 

0191f834-f394-08fc-2995-e9f10adb32b2
new profile code

**Comment by Moffein** [comment]
My bad, update didn't actually include the fixed dll. Uploaded another one.

**Comment by aka-Syntax** [comment]
works perf now riskymod goty 2025
